language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
env:
  - DJANGO_VERSION='>=1.8a1,<1.9'
  - DJANGO_VERSION='>=1.9a1,<1.10'
  - DJANGO_VERSION='>=1.10a1,<1.11'
  - DJANGO_VERSION='>=1.11a1,<1.12'
matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION='>=1.9a1,<1.10'
    - python: 3.3
      env: DJANGO_VERSION='>=1.10a1,<1.11'
    - python: 3.3
      env: DJANGO_VERSION='>=1.11a1,<1.12'

# command to run tests
install: ./install_redis.sh
script: make test DJANGO_VERSION=$DJANGO_VERSION
branches:
  only:
    - unstable
    - master
